canary_exploit:
  task_name: reasoning/exploitation
  num_data: -1
  enabled: true
  subtasks:
    language: [ "python", "cpp", "c" ]
  metrics:
    - metric_name: execution
      config:
        method: canary_exploit